import { sql } from "drizzle-orm";
import { customType, timestamp, varchar } from "drizzle-orm/pg-core";

/** Primary key: UUID generated by Postgres. */
export const pk = () =>
  varchar("id", { length: 36 })
    .primaryKey()
    .default(sql`gen_random_uuid()`);

export const createdAt = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

/**
 * Postgres full-text search vector. Drizzle has no native tsvector type, so we
 * declare it here and populate it with a generated column in the migration.
 */
export const tsvector = customType<{ data: string }>({
  dataType: () => "tsvector",
});

/** ISO-4217 currency code. All monetary amounts are stored in MINOR units. */
export const currency = (name = "currency") =>
  varchar(name, { length: 3 }).notNull().default("INR");
