import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
  vector,
} from "drizzle-orm/pg-core";
import { EMBEDDING_DIMENSIONS } from "@/lib/env";
import { createdAt, currency, pk, tsvector, updatedAt } from "./_shared";
import { merchants } from "./merchant";

export const productStatus = pgEnum("product_status", ["draft", "active", "archived"]);

export const products = pgTable(
  "products",
  {
    id: pk(),
    merchantId: varchar("merchant_id", { length: 36 })
      .notNull()
      .references(() => merchants.id, { onDelete: "cascade" }),
    title: varchar("title", { length: 240 }).notNull(),
    description: text("description").notNull().default(""),
    brand: varchar("brand", { length: 120 }),
    category: varchar("category", { length: 120 }).notNull(),
    /** Free-form structured facts: material, gender, care, features[] … */
    attributes: jsonb("attributes").$type<Record<string, unknown>>().notNull().default({}),
    imageUrls: jsonb("image_urls").$type<string[]>().notNull().default([]),
    /**
     * Internal search tags.
     *
     * Weighted ABOVE the description in the search vector, so a tag match beats
     * a body match. Kept in their own column rather than stuffed into the
     * description: shoppers read the description, and padding it with keywords
     * would degrade both what they see and what the embedder encodes.
     */
    searchTags: jsonb("search_tags").$type<string[]>().notNull().default([]),
    status: productStatus("status").notNull().default("active"),
    ratingBp: integer("rating_bp"),
    ratingCount: integer("rating_count").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("products_merchant_idx").on(t.merchantId),
    index("products_category_idx").on(t.category),
  ],
);

/**
 * A purchasable SKU. Price and inventory live at the variant level because
 * "size 10 in black" is what an agent actually needs to check and buy.
 */
export const productVariants = pgTable(
  "product_variants",
  {
    id: pk(),
    productId: varchar("product_id", { length: 36 })
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    sku: varchar("sku", { length: 80 }).notNull(),
    /** e.g. { size: "10", color: "black" } — the axes agents filter on. */
    attributes: jsonb("attributes").$type<Record<string, string>>().notNull().default({}),
    priceMinor: integer("price_minor").notNull(),
    compareAtPriceMinor: integer("compare_at_price_minor"),
    currency: currency(),
    barcode: varchar("barcode", { length: 64 }),
    active: boolean("active").notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex("variants_sku_idx").on(t.sku),
    index("variants_product_idx").on(t.productId),
    index("variants_price_idx").on(t.priceMinor),
  ],
);

export const inventory = pgTable("inventory", {
  variantId: varchar("variant_id", { length: 36 })
    .primaryKey()
    .references(() => productVariants.id, { onDelete: "cascade" }),
  /** On-hand units. Available = quantity - reserved. */
  quantity: integer("quantity").notNull().default(0),
  /** Held by in-flight checkout sessions; released on expiry or failure. */
  reserved: integer("reserved").notNull().default(0),
  lowStockThreshold: integer("low_stock_threshold").notNull().default(5),
  restockEta: timestamp("restock_eta", { withTimezone: true }),
  updatedAt: updatedAt(),
});

/** Optional sale windows — a variant can exist but not be purchasable today. */
export const availabilityWindows = pgTable(
  "availability_windows",
  {
    id: pk(),
    variantId: varchar("variant_id", { length: 36 })
      .notNull()
      .references(() => productVariants.id, { onDelete: "cascade" }),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
  },
  (t) => [index("availability_variant_idx").on(t.variantId)],
);

/**
 * The AI-readable catalog row: one per product.
 *
 * `aiText` is generated by the normalizer from merchant-authored data — nobody
 * hand-writes it. `embedding` powers semantic recall, `searchVector` powers
 * lexical recall; the two are fused at query time.
 */
export const catalogDocuments = pgTable(
  "catalog_documents",
  {
    productId: varchar("product_id", { length: 36 })
      .primaryKey()
      .references(() => products.id, { onDelete: "cascade" }),
    merchantId: varchar("merchant_id", { length: 36 })
      .notNull()
      .references(() => merchants.id, { onDelete: "cascade" }),
    aiText: text("ai_text").notNull(),
    /** Title and tags, held apart so they can carry weight 'A'. */
    titleText: text("title_text").notNull().default(""),
    tagsText: text("tags_text").notNull().default(""),
    embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
    /**
     * Weighted full-text vector.
     *
     * ts_rank scores weight 'A' at 1.0 and 'B' at 0.4, so a query term matching
     * the title or a tag outranks the same term appearing in the body copy.
     */
    searchVector: tsvector("search_vector").generatedAlwaysAs(
      sql`setweight(to_tsvector('english', coalesce(title_text, '')), 'A')
       || setweight(to_tsvector('english', coalesce(tags_text, '')), 'A')
       || setweight(to_tsvector('english', ai_text), 'B')`,
    ),
    /** Hash of the source data; lets the pipeline skip unchanged products. */
    sourceHash: varchar("source_hash", { length: 64 }).notNull(),
    embeddedAt: timestamp("embedded_at", { withTimezone: true }),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("catalog_search_idx").using("gin", t.searchVector),
    index("catalog_embedding_idx").using(
      "hnsw",
      t.embedding.op("vector_cosine_ops"),
    ),
  ],
);

export const productsRelations = relations(products, ({ one, many }) => ({
  merchant: one(merchants, { fields: [products.merchantId], references: [merchants.id] }),
  variants: many(productVariants),
  document: one(catalogDocuments, {
    fields: [products.id],
    references: [catalogDocuments.productId],
  }),
}));

export const productVariantsRelations = relations(productVariants, ({ one }) => ({
  product: one(products, { fields: [productVariants.productId], references: [products.id] }),
  inventory: one(inventory, {
    fields: [productVariants.id],
    references: [inventory.variantId],
  }),
}));
