import type { MerchantSeed, ProductTemplate } from "./seed-data";

/**
 * Additional marketplace depth.
 *
 * Kept separate from the original seed so it can be applied ADDITIVELY — a full
 * re-seed truncates every table, which would delete real accounts and orders.
 */

const APPAREL_SIZES = ["S", "M", "L", "XL"];

export const EXTRA_MERCHANTS: MerchantSeed[] = [
  {
    slug: "lumen-beauty",
    name: "Lumen Beauty",
    description: "Dermatologist-tested skincare and cosmetics. Cruelty-free, fragrance-optional.",
    supportEmail: "care@lumenbeauty.test",
    priceIndex: 1.08,
    fulfillmentRateBp: 9650,
    avgDispatchHours: 20,
    policies: {
      returnWindowDays: 14,
      returnsAccepted: true,
      returnPolicyText: "14-day returns on unopened products; opened skincare cannot be returned.",
      shippingPolicyText: "Dispatched within 24 hours, temperature-protected packaging.",
      freeShippingAboveMinor: 99900,
      flatShippingMinor: 6900,
      standardDeliveryDays: 3,
      warrantyText: "Batch-tested; replacements for damaged deliveries.",
      cancellationText: "Cancel free before dispatch.",
    },
  },
  {
    slug: "paperbound",
    name: "Paperbound",
    description: "Independent bookshop and stationery counter. Curated, not algorithmic.",
    supportEmail: "hello@paperbound.test",
    priceIndex: 0.98,
    fulfillmentRateBp: 9400,
    avgDispatchHours: 40,
    policies: {
      returnWindowDays: 10,
      returnsAccepted: true,
      returnPolicyText: "10-day returns on undamaged books.",
      shippingPolicyText: "Packed flat, dispatched within 2 working days.",
      freeShippingAboveMinor: 79900,
      flatShippingMinor: 4900,
      standardDeliveryDays: 5,
      warrantyText: "Printing defects replaced free.",
      cancellationText: "Cancellation allowed before dispatch.",
    },
  },
  {
    slug: "cook-and-co",
    name: "Cook & Co",
    description: "Small kitchen appliances and prep tools for people who actually cook.",
    supportEmail: "support@cookandco.test",
    priceIndex: 1.02,
    fulfillmentRateBp: 9550,
    avgDispatchHours: 28,
    policies: {
      returnWindowDays: 15,
      returnsAccepted: true,
      returnPolicyText: "15-day returns; appliances must be unused with original packaging.",
      shippingPolicyText: "Dispatch within 36 hours, insured courier.",
      freeShippingAboveMinor: 199900,
      flatShippingMinor: 9900,
      standardDeliveryDays: 4,
      warrantyText: "2-year warranty on motors and heating elements.",
      cancellationText: "Free cancellation before dispatch.",
    },
  },
  {
    slug: "pawsome-supply",
    name: "Pawsome Supply",
    description: "Food, toys and care essentials for dogs and cats.",
    supportEmail: "woof@pawsome.test",
    priceIndex: 0.94,
    fulfillmentRateBp: 9200,
    avgDispatchHours: 30,
    policies: {
      returnWindowDays: 7,
      returnsAccepted: true,
      returnPolicyText: "7-day returns on sealed items. Opened food cannot be returned.",
      shippingPolicyText: "Dispatch within 36 hours.",
      freeShippingAboveMinor: 89900,
      flatShippingMinor: 5900,
      standardDeliveryDays: 4,
      warrantyText: "Damaged-on-arrival replacements.",
      cancellationText: "Cancel before dispatch.",
    },
  },
  {
    slug: "tinker-toys",
    name: "Tinker Toys",
    description: "Building sets, puzzles and board games. Age-graded, safety-certified.",
    supportEmail: "play@tinkertoys.test",
    priceIndex: 1.0,
    fulfillmentRateBp: 9450,
    avgDispatchHours: 26,
    policies: {
      returnWindowDays: 20,
      returnsAccepted: true,
      returnPolicyText: "20-day returns on unopened sets.",
      shippingPolicyText: "Gift-wrap available, dispatch within 24 hours.",
      freeShippingAboveMinor: 129900,
      flatShippingMinor: 6900,
      standardDeliveryDays: 4,
      warrantyText: "Missing-piece replacements for 12 months.",
      cancellationText: "Free cancellation before dispatch.",
    },
  },
  {
    slug: "verde-living",
    name: "Verde Living",
    description: "Indoor plants, planters and garden tools, shipped in protective sleeves.",
    supportEmail: "grow@verdeliving.test",
    priceIndex: 1.06,
    fulfillmentRateBp: 9100,
    avgDispatchHours: 48,
    policies: {
      returnWindowDays: 5,
      returnsAccepted: true,
      returnPolicyText: "5-day guarantee on live plants arriving damaged, with a photo.",
      shippingPolicyText: "Live plants ship Monday to Wednesday only.",
      freeShippingAboveMinor: 149900,
      flatShippingMinor: 8900,
      standardDeliveryDays: 6,
      warrantyText: "30-day replacement if a plant fails to establish.",
      cancellationText: "Cancel before the plant is packed.",
    },
  },
];

export const EXTRA_PRODUCTS: ProductTemplate[] = [
  // ------------------------------------------------------------------ beauty
  {
    key: "vitamin-c-serum",
    title: "15% Vitamin C Brightening Serum",
    brand: "Lumen",
    category: "Skincare",
    description:
      "Stabilised 15% L-ascorbic acid serum with ferulic acid and vitamin E. Targets dullness and uneven tone. Fragrance-free, suitable for daily morning use under sunscreen.",
    attributes: {
      volumeMl: 30,
      activeIngredient: "L-ascorbic acid 15%",
      fragranceFree: true,
      skinType: "all",
      features: ["brightening", "antioxidant", "fragrance-free"],
    },
    basePriceMinor: 129900,
    axes: [{ name: "size", values: ["30ml", "50ml"] }],
    merchants: ["lumen-beauty"],
    demand: 11,
  },
  {
    key: "ceramide-moisturiser",
    title: "Ceramide Repair Moisturiser",
    brand: "Lumen",
    category: "Skincare",
    description:
      "Rich barrier-repair cream with three ceramides, niacinamide and squalane. Non-comedogenic, unscented, formulated for dry and compromised skin.",
    attributes: {
      volumeMl: 50,
      skinType: "dry",
      nonComedogenic: true,
      features: ["barrier repair", "niacinamide", "unscented"],
    },
    basePriceMinor: 89900,
    axes: [{ name: "size", values: ["50ml"] }],
    merchants: ["lumen-beauty"],
    demand: 9,
  },
  {
    key: "mineral-sunscreen",
    title: "SPF 50 Mineral Sunscreen",
    brand: "Lumen",
    category: "Sun Care",
    description:
      "Broad-spectrum SPF 50 zinc oxide sunscreen with no white cast. Water-resistant for 40 minutes, reef-safe formulation.",
    attributes: { spf: 50, mineral: true, waterResistantMinutes: 40, reefSafe: true },
    basePriceMinor: 74900,
    axes: [{ name: "size", values: ["50ml", "100ml"] }],
    merchants: ["lumen-beauty"],
    demand: 13,
  },
  // ------------------------------------------------------------------- books
  {
    key: "atlas-of-cities",
    title: "An Atlas of Imagined Cities",
    brand: "Paperbound",
    category: "Books",
    description:
      "Large-format illustrated hardback mapping fictional cities from literature, with essays on how writers build place. 320 pages, thread-sewn binding.",
    attributes: { format: "hardback", pages: 320, illustrated: true, language: "English" },
    basePriceMinor: 149900,
    axes: [{ name: "format", values: ["hardback", "paperback"] }],
    merchants: ["paperbound"],
    demand: 6,
  },
  {
    key: "notebook-dotgrid",
    title: "A5 Dot-Grid Notebook",
    brand: "Paperbound",
    category: "Stationery",
    description:
      "160 gsm bleed-resistant dot-grid notebook, 192 pages, lies flat when open. Suitable for fountain pens.",
    attributes: { gsm: 160, pages: 192, layout: "dot grid", laysFlat: true },
    basePriceMinor: 64900,
    axes: [
      { name: "color", values: ["black", "navy", "sage"] },
      { name: "size", values: ["A5", "A4"] },
    ],
    merchants: ["paperbound", "urban-outfit-co"],
    demand: 14,
  },
  {
    key: "fountain-pen",
    title: "Brass Fountain Pen",
    brand: "Paperbound",
    category: "Stationery",
    description:
      "Solid brass fountain pen with a medium steel nib, converter and cartridge compatible. Develops a patina with use.",
    attributes: { material: "brass", nib: "medium", refillable: true },
    basePriceMinor: 189900,
    axes: [{ name: "color", values: ["brass", "black"] }],
    merchants: ["paperbound"],
    demand: 5,
  },
  // -------------------------------------------------------------- appliances
  {
    key: "espresso-machine",
    title: "Compact Espresso Machine",
    brand: "Cook",
    category: "Kitchen Appliances",
    description:
      "15-bar pump espresso machine with a thermoblock heater, steam wand and 1.4-litre removable tank. Heats up in 30 seconds.",
    attributes: { pressureBar: 15, tankLitres: 1.4, steamWand: true, heatUpSeconds: 30 },
    basePriceMinor: 1499900,
    axes: [{ name: "color", values: ["black", "steel"] }],
    merchants: ["cook-and-co"],
    demand: 4,
  },
  {
    key: "stand-mixer",
    title: "5L Tilt-Head Stand Mixer",
    brand: "Cook",
    category: "Kitchen Appliances",
    description:
      "1000-watt stand mixer with a 5-litre stainless bowl, 10 speeds, and dough hook, whisk and beater included.",
    attributes: { watts: 1000, bowlLitres: 5, speeds: 10, attachments: 3 },
    basePriceMinor: 1899900,
    axes: [{ name: "color", values: ["cream", "red", "black"] }],
    merchants: ["cook-and-co"],
    demand: 3,
  },
  {
    key: "chef-knife",
    title: "8-inch Damascus Chef Knife",
    brand: "Cook",
    category: "Cookware",
    description:
      "67-layer Damascus steel chef knife with a VG-10 core, hardened to 60 HRC, with a stabilised wood handle and full tang.",
    attributes: { lengthInches: 8, steel: "VG-10 core, 67-layer", hardnessHrc: 60, fullTang: true },
    basePriceMinor: 649900,
    axes: [{ name: "size", values: ["8 inch", "6 inch"] }],
    merchants: ["cook-and-co", "hearth-and-home"],
    demand: 7,
  },
  {
    key: "air-fryer",
    title: "6L Digital Air Fryer",
    brand: "Cook",
    category: "Kitchen Appliances",
    description:
      "6-litre air fryer with eight presets, a 200°C maximum and a dishwasher-safe non-stick basket.",
    attributes: { capacityLitres: 6, maxTempC: 200, presets: 8, dishwasherSafe: true },
    basePriceMinor: 899900,
    axes: [{ name: "color", values: ["black", "white"] }],
    merchants: ["cook-and-co", "hearth-and-home"],
    demand: 10,
  },
  // -------------------------------------------------------------------- pets
  {
    key: "orthopedic-dog-bed",
    title: "Orthopaedic Memory Foam Dog Bed",
    brand: "Pawsome",
    category: "Pet Furniture",
    description:
      "Memory foam dog bed with a bolstered rim and a removable, machine-washable waterproof cover. Supports older joints.",
    attributes: { fill: "memory foam", washableCover: true, waterproofLiner: true },
    basePriceMinor: 349900,
    axes: [
      { name: "size", values: ["M", "L", "XL"] },
      { name: "color", values: ["grey", "beige"] },
    ],
    merchants: ["pawsome-supply"],
    demand: 8,
  },
  {
    key: "cat-tree",
    title: "Multi-Level Cat Tree",
    brand: "Pawsome",
    category: "Pet Furniture",
    description:
      "1.4-metre cat tree with sisal scratching posts, two hammocks and a covered den. Anti-tip wall strap included.",
    attributes: { heightCm: 140, levels: 4, sisalPosts: 3, antiTipStrap: true },
    basePriceMinor: 549900,
    axes: [{ name: "color", values: ["beige", "grey"] }],
    merchants: ["pawsome-supply"],
    demand: 5,
  },
  {
    key: "slow-feeder-bowl",
    title: "Slow Feeder Dog Bowl",
    brand: "Pawsome",
    category: "Pet Accessories",
    description:
      "Maze-pattern slow feeder that extends mealtimes roughly tenfold, reducing bloat and gulping. Food-grade, dishwasher safe.",
    attributes: { material: "food-grade ABS", dishwasherSafe: true, nonSlipBase: true },
    basePriceMinor: 59900,
    axes: [{ name: "color", values: ["teal", "orange", "grey"] }],
    merchants: ["pawsome-supply"],
    demand: 12,
  },
  // -------------------------------------------------------------------- toys
  {
    key: "marble-run",
    title: "Wooden Marble Run Set",
    brand: "Tinker",
    category: "Toys",
    description:
      "68-piece beech marble run with interchangeable chutes and funnels. Ages 4 and up, no batteries required.",
    attributes: { pieces: 68, material: "beech wood", minAge: 4, batteriesRequired: false },
    basePriceMinor: 349900,
    axes: [{ name: "size", values: ["68 piece", "120 piece"] }],
    merchants: ["tinker-toys"],
    demand: 9,
  },
  {
    key: "strategy-board-game",
    title: "Settlers of the Tide Board Game",
    brand: "Tinker",
    category: "Board Games",
    description:
      "Strategy board game for 2 to 5 players, 60 to 90 minutes per game. Tile-laying and trading with a tidal board that shifts each round.",
    attributes: { players: "2-5", minutes: "60-90", minAge: 10, expansionCompatible: true },
    basePriceMinor: 279900,
    axes: [{ name: "edition", values: ["standard", "deluxe"] }],
    merchants: ["tinker-toys"],
    demand: 7,
  },
  {
    key: "science-kit",
    title: "Junior Chemistry Science Kit",
    brand: "Tinker",
    category: "Toys",
    description:
      "45 guided experiments with safe reagents, goggles and a full-colour lab manual. Ages 8 and up, adult supervision advised.",
    attributes: { experiments: 45, minAge: 8, safetyGogglesIncluded: true },
    basePriceMinor: 219900,
    axes: [{ name: "size", values: ["standard"] }],
    merchants: ["tinker-toys"],
    demand: 6,
  },
  // ------------------------------------------------------------------ garden
  {
    key: "monstera-plant",
    title: "Monstera Deliciosa in Ceramic Pot",
    brand: "Verde",
    category: "Indoor Plants",
    description:
      "Established Monstera deliciosa, roughly 60 cm tall, in a matte ceramic pot with drainage. Tolerates indirect light and infrequent watering.",
    attributes: {
      heightCm: 60,
      light: "bright indirect",
      wateringDays: 10,
      petSafe: false,
      potIncluded: true,
    },
    basePriceMinor: 189900,
    axes: [{ name: "color", values: ["white", "terracotta"] }],
    merchants: ["verde-living"],
    demand: 10,
  },
  {
    key: "snake-plant",
    title: "Snake Plant (Sansevieria)",
    brand: "Verde",
    category: "Indoor Plants",
    description:
      "Near-indestructible snake plant, 45 cm tall. Tolerates low light and weeks without water; filters indoor air.",
    attributes: { heightCm: 45, light: "low to bright", wateringDays: 21, petSafe: false },
    basePriceMinor: 119900,
    axes: [{ name: "color", values: ["white", "black"] }],
    merchants: ["verde-living"],
    demand: 11,
  },
  {
    key: "pruning-shears",
    title: "Bypass Pruning Shears",
    brand: "Verde",
    category: "Garden Tools",
    description:
      "Forged carbon steel bypass shears with a non-stick blade coating, sap groove and a shock-absorbing bumper. Cuts up to 20 mm.",
    attributes: { maxCutMm: 20, steel: "carbon", bypass: true, sapGroove: true },
    basePriceMinor: 99900,
    axes: [{ name: "size", values: ["standard"] }],
    merchants: ["verde-living", "peak-gear"],
    demand: 8,
  },
  // ------------------------------------ cross-listings into existing shops
  {
    key: "merino-base-layer",
    title: "Merino Wool Base Layer",
    brand: "Peak",
    category: "Activewear",
    description:
      "190 gsm merino wool base layer with flatlock seams. Regulates temperature, resists odour over multiple days of wear.",
    attributes: { gsm: 190, fabric: "merino wool", odourResistant: true, gender: "unisex" },
    basePriceMinor: 349900,
    axes: [
      { name: "size", values: APPAREL_SIZES },
      { name: "color", values: ["black", "charcoal"] },
    ],
    merchants: ["peak-gear", "stride-athletics"],
    demand: 7,
  },
  {
    key: "resistance-band-set",
    title: "Resistance Band Set",
    brand: "Stride",
    category: "Fitness Accessories",
    description:
      "Five latex resistance bands from 5 to 35 kg, with door anchor, handles and ankle straps in a carry bag.",
    attributes: { bands: 5, resistanceKg: "5-35", accessoriesIncluded: true },
    basePriceMinor: 119900,
    axes: [{ name: "size", values: ["standard"] }],
    merchants: ["stride-athletics", "budget-bazaar"],
    demand: 13,
  },
];
